CREATE TABLE tb_rh(
id BIGINT AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL, 
cargo VARCHAR(150) NOT NULL,
setor VARCHAR(150) NOT NULL,
anoDeServico INT, 
salario DECIMAL(6,2) NOT NULL,
PRIMARY KEY (id)
);
